export const HOME_PROP_CHANGED = 'HOME_PROP_CHANGED'
export const GET_NEW_SUGGESTION_START = 'GET_NEW_SUGGESTION_START'
export const GET_NEW_SUGGESTION_SUCCESS = 'GET_NEW_SUGGESTION_SUCCESS'
export const GET_NEW_SUGGESTION_FAILED = 'GET_NEW_SUGGESTION_FAILED'
